### PR TITLE
ban sleepybear

### PR DESCRIPTION
**Pull request by OkiStuff**

### CODE REVIEW

**Comment by OkiStuff** [comment]
i dont think sleepy can get past this cause it blocks his id

**Comment by FluentCoding** [comment]
lol

**Review by nicefellow5 — APPROVED** [review]

**Comment by OkiStuff** [comment]
@benawad merge the code please :(

**Review by ThatCopy — APPROVED** [review]

**Comment by rpush-01** [comment]
very important, must be merged immediately.

**Comment by varaprasadh** [comment]
@rpush-01 yup, they did. reviewers must be kidding with contributors.

**Comment by varaprasadh** [comment]
it's the best way to ban someone. i learned new stuff. lol. @bar9 you did a great job banning this PR.

**Comment by OkiStuff** [comment]
smh sleepybear needs to be banned!!

**Comment by TheFern2** [comment]
Thanks all for the feedback.

Folks the backend api is also on github, blocking an id wouldn't do much on the extension as the extension is also open source and can be forked and recompiled.

We're are currently working on a road map of things that need to be done, and banning system is one of them but it will be handle in the backend api.

@bar In the interim, I suggest to create another repository where people can submit user ids. Then from the API on line 59 we can check if they are banned.

**Comment by OkiStuff** [comment]
Great choice! sleepybear is a dangerous man.

**Comment by TheFern2** [comment]
Sorry I opened by accident while I was trying to comment.

**Comment by TheFern2** [comment]
What exactly did sleepybear do, just nsfw stuff?

**Comment by varaprasadh** [comment]
@TheFern2  bro,even this is open source, the actual deployed version won't give any access to anyone. re-compiling does'nt matter.

**Comment by TheFern2** [comment]
@varaprasadh Right, I was going back and forth between the repos and I thought I was commenting on the extension repo, not the api. My bad.

**Comment by JackBocresion** [comment]
Bruh Momento

**Pull request closed without merging**
