### PR TITLE
Added issue template and PR template 

### PR DESCRIPTION
**Pull request by ghost**
I have created a PR template and an issue template checkout #24

### CODE REVIEW

**Comment by TheFern2** [comment]
Hey there the templates look great, thanks for the PR. One small issue at the very top, we don't have a slack channel, nor are in maintenance mode.

@bar9 have we thought about opening the discord server?

**Comment by ghost** [comment]
I will edit it and why won't we create a discord server after this issue

**Comment by ghost** [comment]
@TheFern2
Done

**Comment by Bukii** [comment]
> I will edit it and why won't we create a discord server after this issue

There's already a Discord server but it's only open for team members. Maybe it will be open for everyone soon!

**Comment by TheFern2** [comment]
@Bukii Yeah we need to open up the server. I actually think discord servers are public by default, no?

**Comment by TheFern2** [comment]
Let's wait on merging this so we can add discord info on the issue template. Probably can also be on the PR template, in case there are questions too.

**Comment by ghost** [comment]
@TheFern2 
OK

**Comment by ghost** [comment]
@TheFern2 yes I think its public just need the invitation link to join

**Comment by TheFern2** [comment]
Here's the join link https://discord.gg/ABpGdRxvaA

**Comment by ghost** [comment]
@TheFern2 

Thank you i will add

**Comment by ghost** [comment]
@TheFern2 

Done

**Comment by ghost** [comment]
@TheFern2 

Can you make an issue with the discord server and pin it so others would join the server.

**Comment by TheFern2** [comment]
> @TheFern2
> 
> Can you make an issue with the discord server and pin it so others would join the server.

Yes, that is a good idea. Thanks for the PR again!

**Comment by ghost** [comment]
@TheFern2 

Your welcome.

**Pull request merged**
