### PR TITLE
[Feature] GitHub friends full implementation 

### PR DESCRIPTION
**Pull request by Bukii**
**This PR includes:** 🚀
- [x] change the add/remove friend endpoints to use the github api (octokit)
- [x] every github api call takes the user oauthToken for authentication, therefore users are able to make 5000 reqs per hour
- [x] changed the /github/friends endpoint to /text-stories/friends/hot
- [x] /text-stories/friends/hot now returns a list of stories of your friends (like /text-stories/hot); it won't give you a full list, there is also a "has more" button, in order to load more friends stories
- [x] an alert, that tells the user to reauthenticate when they call add/remove friend (it is necessary to have the user:follow scope, therefore they have to reauth)

Also, thanks to @bar9 for helping! :)

### CODE REVIEW

**Comment by TheFern2** [comment]
I am getting some query errors, here's the steps to duplicate:

- wipe stories db
- attempt to launch stories extension from S icon (without authenticating first)
- there are zero stories and zero users in the db, but I don't think it should the below error

Following error is displayed on api console:
```
(node:777164) UnhandledPromiseRejectionWarning: HttpError: Bad credentials
    at /home/fernandob/git/vscode-stories-api/node_modules/@octokit/request/dist-src/fetch-wrapper.js:49:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:777164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:777164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I went ahead and authenticated from one of my dummy accounts, then when hitting S icon I get the following:

```
query: SELECT "User"."id" AS "User_id", "User"."githubId" AS "User_githubId", "User"."username" AS "User_username", "User"."displayName" AS "User_displayName", "User"."profileUrl" AS "User_profileUrl", "User"."photoUrl" AS "User_photoUrl", "User"."githubAccessToken" AS "User_githubAccessToken", "User"."flair" AS "User_flair", "User"."other" AS "User_other", "User"."tokenVersion" AS "User_tokenVersion", "User"."createdAt" AS "User_createdAt", "User"."updatedAt" AS "User_updatedAt" FROM "user" "User" WHERE "User"."id" = $1 LIMIT 1 -- PARAMETERS: ["438a2af6-f04a-4c48-8b5d-c59346552fa7"]                                                                                                
query: select u."id" from "user" u where ;
query failed: select u."id" from "user" u where ;
error: error: syntax error at or near ";"
```

Even though stories panel wasn't working I went ahead and authenticated my main acc, and one more dummy acc and then push stories from all three accounts. The db now holds 3 users and 3 stories, and still got the error below:

```
query failed: 
      select
      ts.id,
      ts."creatorId",
      u.username "creatorUsername",
      u."id" "creatorId",
      u."photoUrl" "creatorAvatarUrl",
      u.flair
      from text_story ts
      inner join "user" u on u.id = ts."creatorId"
      WHERE u."id" IN ('')
      order by (ts."numLikes"+1) / power(EXTRACT(EPOCH FROM current_timestamp-ts."createdAt")/3600,1.8) DESC
      limit 12
      
    
error: error: invalid input syntax for type uuid: ""
    at Parser.parseErrorMessage (/home/fernandob/git/vscode-stories-api/node_modules/pg-protocol/src/parser.ts:357:11)
```

**Comment by Bukii** [comment]
Thanks! Found the bug. It's because the user doesn't have any friends and that's where the error occurs. I need to fix that in the api as well as in the frontend. :)

**Comment by Bukii** [comment]
The "Bad credentials" error happens because you wiped your db ad the "Authorized OAuth Apps" connection, therefore the accessToken will get deleted, but the frontend doesn't know anything regarding the deletetion, so the old accessToken is still stored. Then authenticated? is true and it calls the /text-stories/friends/hot endpoint, which needs a user for the githubAccessToken. The githubAccessToken can't be found because the db is empty.

**Review by TheFern2 — COMMENTED** [review]
Great work @Bukii, a few comments:

- On the routes where we're catching the error, do you think 400 and 404 are the only errors that will ever happen? What happens if another error comes through?

**Comment by Bukii** [comment]
> Great work @Bukii, a few comments:
> 
> - On the routes where we're catching the error, do you think 400 and 404 are the only errors that will ever happen? What happens if another error comes through?

Talking about GitHub errors?

**Comment by TheFern2** [comment]
Yeah let's say we get 403 for whatever reason, we're not handling that so user won't see a vscode message with any error.

**Comment by Bukii** [comment]
If a user doesn't follow anybody, it will return an empty array.
image

Furthermore, you can see the response cases in the docs:
[REST API Docs](https://docs.github.com/en/rest/reference/users#list-the-people-a-user-follows)

**Comment by TheFern2** [comment]
This is kind of both an ui/api issue: if the user you're trying to follow has blocked you, the vscode extension ui doesn't make you aware of this, there is no error or message on the ui, it looks like you can add/remove the friend, but when the refresh button is clicked, that friend doesn't appear on the friend side, because github will not return that friend id if they blocked you.

Not sure if the ideal solution would be to make the button not clickable if the user has blocked you?

**Comment by Bukii** [comment]
> This is kind of both an ui/api issue: if the user you're trying to follow has blocked you, the vscode extension ui doesn't make you aware of this, there is no error or message on the ui, it looks like you can add/remove the friend, but when the refresh button is clicked, that friend doesn't appear on the friend side, because github will not return that friend id if they blocked you.
> 
> Not sure if the ideal solution would be to make the button not clickable if the user has blocked you?

My findings:
- If you follow a user the button will turn to a remove button, but if you reload the panel/stories and click on the same story again there's the add button again, because if someone has blocked you, you can't follow this user and your follow will get deleted
- There isn't really a way of finding out if someone has blocked you I guess
- You are only allowed to get the users you blocked [reference](https://docs.github.com/en/rest/reference/users#blocking-users)
- The only way it might work is to check if you really follow this person after the actual add/remove call. But idk if that's worth it

**Comment by TheFern2** [comment]
> > This is kind of both an ui/api issue: if the user you're trying to follow has blocked you, the vscode extension ui doesn't make you aware of this, there is no error or message on the ui, it looks like you can add/remove the friend, but when the refresh button is clicked, that friend doesn't appear on the friend side, because github will not return that friend id if they blocked you.
> > Not sure if the ideal solution would be to make the button not clickable if the user has blocked you?
> 
> My findings:
> 
>     * If you follow a user the button will turn to a remove button, but if you reload the panel/stories and click on the same story again there's the add button again, because if someone has blocked you, you can't follow this user and your follow will get deleted
> 
>     * There isn't really a way of finding out if someone has blocked you I guess
> 
>     * You are only allowed to get the users you blocked [reference](https://docs.github.com/en/rest/reference/users#blocking-users)
> 
>     * The only way it might work is to check if you really follow this person after the actual add/remove call. But idk if that's worth it

Yeah the github api is a bit strange, in my opinion is a bug in the api, it should return some type of 400 code like 403 or 405, definitely not 204. Or maybe that's how they wanted it doesn't make sense, I just blocked my main acc from a dummy user, logged in with my main acc and I can still see the user. I think this blocking only matters for mentions, and repository stuff.

Only think I could think of, is to call the "/is-friend/:username" route, right after add/remove friend just to make sure that user id is returned in the array. If it isn't then we can present a message like "something went wrong, please check you can follow the user in the browser". If a user blocks you, the follow button doesn't appear in the browser.

**Comment by Bukii** [comment]
Yeah, that's what I thought of. But is it worth it? Is it worth the extra time it needs for the second req?

**Comment by anubra266** [comment]
@Bukii  If `user A` blocks `User B`, `User A` no longer exists to `User B`, he can't find him, I'm guessing `User B` querying for `User A` returns null, so why can't we hide that button based on that result.
Please correct me If I'm mistaken.

**Comment by TheFern2** [comment]
> Yeah, that's what I thought of. But is it worth it? Is it worth the time?

I think is worth the time, otherwise we're letting the user think they're following someone when they might not be. And we're not presenting any errors or messages. So in the end is bad UX, is not your fault, github api should give a better response tbh. Is like they added the blocking feature but only did it half way through.

I think we should call the is-friend route like you had in onMount but when pressing the button, if is false when we're expecting it to be true, then we can present a vscode message/error:

```
  try {
    await mutation(`/add-friend/${story.creatorUsername}`, {});
    isFriend = true; <= Call is-friend route here, and update this variable
  } catch {}
```

**Comment by TheFern2** [comment]
@anubra266 the github api is bad in regards to the follow. It always returns 204 whether the user has blocked you or not. Imo this is a bug in the api, it doesn't make any sense to return the same response for different outcomes.

Also github doesn't hide users if they blocked you, I believe it only limits repo interaction and ability to @ users. Users are still all visible.

**Comment by anubra266** [comment]
> @anubra266 the github api is bad in regards to the follow. It always returns 204 whether the user has blocked you or not. Imo this is a bug in the api, it doesn't make any sense to return the same response for different outcomes.
> 
> Also github doesn't hide users if they blocked you, I believe it only limits repo interaction and ability to @ users. Users are still all visible.

Woah. How can one report the bug though?
So therecan be updates later.

**Comment by TheFern2** [comment]
@anubra266 That's a good question, I've never filed an api bug in github.

**Comment by Bukii** [comment]
> > Yeah, that's what I thought of. But is it worth it? Is it worth the time?
> 
> I think is worth the time, otherwise we're letting the user think they're following someone when they might not be. And we're not presenting any errors or messages. So in the end is bad UX, is not your fault, github api should give a better response tbh. Is like they added the blocking feature but only did it half way through.
> 
> I think we should call the is-friend route like you had in onMount but when pressing the button, if is false when we're expecting it to be true, then we can present a vscode message/error:
> 
> ```
>   try {
>     await mutation(`/add-friend/${story.creatorUsername}`, {});
>     isFriend = true; <= Call is-friend route here, and update this variable
>   } catch {}
> ```

Added your idea to frontend pr 👍

**Pull request merged**
